### ISSUE TITLE
Add a boolean setting that allows coins to be created for NPCs as well

### ISSUE THREAD

**Issue by kristianserrano** [ddbrown30/sfc#28]
Currently, coins.js seems to restrict coin items being created to characters only. It would be nice to have a boolean setting that allows the module to create coins for NPCs as well. This could help with scenarios where an NPC has something like 2 gp and 8 sp.

**Comment by ddbrown30** [comment]
This is more involved than just adding a setting in order to do it right. The default NPC sheet really doesn't work with the display so I would need to craft something completely new, detect when I'm using the NPC sheet (if that's possible), and then use that display instead of the default one.

That said, I'm not against NPCs using currencies. I only set it up this way to simplify the module because I figured most people wouldn't care about that level of bookkeeping directly in their NPC actors. If you want to take on that work and make a PR for it, I'll take it so long as it looks good and doesn't impact the existing player systems.

**Comment by kristianserrano** [comment]
I've got a branch in which it only applies the changes to the sheet if the NPC is using an official SWADE character sheet, which is now possible.

**Comment by ddbrown30** [comment]
Cool cool. I think I'd be fine with that. Send me the PR when it's ready and I'll have a look.

**Comment by kristianserrano** [comment]
Finally got around to that PR!
